/* KHALID CLOUD v3 — Supabase autenticado, sincronização segura e anti-duplicação. */
(function(){
  const SUPABASE_URL='https://kwuxixucspzqfhzxkimc.supabase.co';
  const SUPABASE_KEY='sb_publishable_vsenwbLiBHSyiZrqDvhtyQ_fgiABbrh';
  const AUTH_SESSION='khalidAuthSession';
  const isLogin=/\/login\.html$/i.test(location.pathname)||location.pathname.endsWith('/');
  const TABLES={sistemaKhalidCondominios:'condominios',sistemaKhalidInspecoes:'inspecoes',sistemaKhalidOcorrencias:'ocorrencias',khalidTreinamentos:'treinamentos'};
  const originalSet=Storage.prototype.setItem;
  let syncing=false;
  function session(){try{return JSON.parse(localStorage.getItem(AUTH_SESSION)||'null')}catch(e){return null}}
  function token(){return session()?.access_token||''}
  async function authGuard(){if(isLogin)return true;const s=session();if(!s?.access_token){location.replace('login.html');return false}try{const r=await fetch(SUPABASE_URL+'/auth/v1/user',{headers:{apikey:SUPABASE_KEY,Authorization:'Bearer '+s.access_token}});if(r.ok)return true;localStorage.removeItem(AUTH_SESSION);location.replace('login.html');return false}catch(e){console.warn('KHALID Auth indisponível',e);return true}}
  function read(k){try{const v=JSON.parse(localStorage.getItem(k)||'[]');return Array.isArray(v)?v:[]}catch(e){return[]}}
  function write(k,v){originalSet.call(localStorage,k,JSON.stringify(v))}
  function clean(v){return String(v??'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ')}
  function iso(v){if(!v)return new Date().toISOString();const d=new Date(v);return isNaN(d)?new Date().toISOString():d.toISOString()}
  function fp(k,x){if(k==='sistemaKhalidCondominios')return 'c|'+clean(x.nome||x.name)+'|'+clean(x.endereco);if(k==='sistemaKhalidInspecoes')return 'i|'+clean(x.condominio_nome||x.condominio)+'|'+iso(x.data_inspecao||x.data)+'|'+clean(x.inspetor||x.supervisor)+'|'+clean(x.resultado||x.status)+'|'+clean(x.observacoes||x.descricao);if(k==='sistemaKhalidOcorrencias')return 'o|'+clean(x.condominio_nome||x.condominio)+'|'+iso(x.data_ocorrencia||x.data)+'|'+clean(x.categoria||x.tipo)+'|'+clean(x.titulo||x.assunto)+'|'+clean(x.descricao||x.relato);if(k==='khalidTreinamentos')return 't|'+clean(x.colaborador_nome||x.colaborador||x.nome)+'|'+clean(x.re||x.RE)+'|'+clean(x.curso||x.tipo)+'|'+clean(x.data_treinamento||x.data)+'|'+clean(x.condominio_nome||x.condominio);return JSON.stringify(x)}
  function toCloud(k,x){if(k==='sistemaKhalidCondominios')return {nome:x.nome||x.name||'',endereco:x.endereco||'',zona:x.zona||'',circuito:x.circuito||'',ordem:x.ordem??null,latitude:x.latitude??null,longitude:x.longitude??null,ativo:x.ativo!==false};if(k==='sistemaKhalidInspecoes')return {condominio_nome:x.condominio_nome||x.condominio||'',data_inspecao:iso(x.data_inspecao||x.data||x.created_at),inspetor:x.inspetor||x.supervisor||'Khalid',resultado:x.resultado||x.status||'',observacoes:x.observacoes||x.descricao||'',itens:x.itens||{}};if(k==='sistemaKhalidOcorrencias')return {condominio_nome:x.condominio_nome||x.condominio||'',data_ocorrencia:iso(x.data_ocorrencia||x.data||x.created_at),categoria:x.categoria||x.tipo||'',titulo:x.titulo||x.assunto||'',descricao:x.descricao||x.relato||'',providencias:x.providencias||'',responsavel:x.responsavel||x.inspetor||'Khalid',prioridade:x.prioridade||x.gravidade||'',status:x.status||'aberta'};if(k==='khalidTreinamentos')return {colaborador_nome:x.colaborador_nome||x.colaborador||x.nome||'',re:x.re||x.RE||'',condominio_nome:x.condominio_nome||x.condominio||'',curso:x.curso||x.tipo||'Treinamento',carga_horaria:x.carga_horaria||x.horas||null,instrutor:x.instrutor||'',data_treinamento:x.data_treinamento||x.data||null,status:x.status||'Concluído',conteudo:x.conteudo||[],observacoes:x.observacoes||x.obs||''}}
  function fromCloud(k,x){if(k==='sistemaKhalidCondominios')return {...x};if(k==='sistemaKhalidInspecoes')return {...x,id:x.id,data:x.data_inspecao,condominio:x.condominio_nome};if(k==='sistemaKhalidOcorrencias')return {...x,id:x.id,data:x.data_ocorrencia,condominio:x.condominio_nome,gravidade:x.prioridade,tipo:x.categoria};if(k==='khalidTreinamentos')return {...x,id:x.id,colaborador:x.colaborador_nome,condominio:x.condominio_nome,re:x.re,horas:x.carga_horaria,data:x.data_treinamento,obs:x.observacoes}}
  function headers(extra={}){const t=token();return {apikey:SUPABASE_KEY,Authorization:'Bearer '+(t||SUPABASE_KEY),'Content-Type':'application/json',...extra}}
  async function req(table,method,body){if(!token())throw new Error('Sessão não autenticada');const r=await fetch(SUPABASE_URL+'/rest/v1/'+table,{method,headers:headers({'Prefer':'return=representation'}),...(body!==undefined?{body:JSON.stringify(body)}:{})});if(!r.ok)throw new Error(await r.text());return r.status===204?[]:r.json()}
  async function syncKey(k){const table=TABLES[k];if(!table||!token())return;const local=read(k);const cloud=await req(table,'GET');const cloudUnique=new Map();for(const x of cloud){const f=fp(k,x);if(!cloudUnique.has(f))cloudUnique.set(f,x)}const localUnique=new Map();for(const x of local)localUnique.set(fp(k,x),x);for(const [f,x] of localUnique){if(!cloudUnique.has(f)){try{const created=await req(table,'POST',toCloud(k,x));const y=Array.isArray(created)?created[0]:created;if(y)cloudUnique.set(f,y)}catch(e){console.warn('KHALID CLOUD upload',table,e)}}}const fresh=await req(table,'GET');const merged=new Map();for(const x of fresh){const f=fp(k,x);if(!merged.has(f))merged.set(f,fromCloud(k,x))}write(k,Array.from(merged.values()))}
  async function syncAll(){if(syncing||!token())return;syncing=true;try{for(const k of Object.keys(TABLES))await syncKey(k);originalSet.call(localStorage,'khalidCloudLastSync',new Date().toISOString());window.dispatchEvent(new CustomEvent('khalid-cloud-synced'))}catch(e){console.warn('KHALID CLOUD indisponível:',e)}finally{syncing=false}}
  Storage.prototype.setItem=function(k,v){originalSet.call(this,k,v);if(!syncing&&TABLES[k]&&token())Promise.resolve().then(()=>syncKey(k)).catch(e=>console.warn('KHALID CLOUD',e))};
  window.KhalidCloud={syncAll,syncKey,url:SUPABASE_URL,online:true,session:session};
  authGuard().then(ok=>{if(ok){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',syncAll);else syncAll();setInterval(syncAll,60000)}});
})();